name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup dependencies
        run: npm ci

      - name: Lint
        run: npm run check

      - name: Test
        run: npm run test

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            USERNAME
            PASSWORD
          command: deploy --minify src/index.ts
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGFLARE_API_KEY: ${{ secrets.LOGFLARE_API_KEY }}
          LOGFLARE_SOURCE: ${{ secrets.LOGFLARE_SOURCE }}
